### PR TITLE
Adding a new chapter "How it is working"

### PR DESCRIPTION
**Pull request by applikationsprogramvara**
I was really inspired by the library, so I tried to figure out how it is working. Unfortunately any explanation was missing in the repository. So made some notes about the common ideas, how it is working.

Could you take a look and check if there is no total heresy? I hope it would be useful for the community.

I would consider adding some diagrams and pictures to this chapter later.

### CODE REVIEW

**Comment by Dmitry-Borodin** [comment]
Thank you for the PR.
This is in general right description. I think it make sense to move it to another md file and just put the reference in readme, since most people reading it before they use it, and they are not interested in implementation details. It's always nice to have single responsibility in documentation as well.
Would you mind doing it?

If you interested digging in - you can consider checking some [issues](https://github.com/Dmitry-Borodin/pdfview-android/issues) - like supporting different sized pages (we can add another mode that will open all pages on init and remember sizes or try to use the biggest one, just have it off by default for performance reason.
Or adding page numbers or page separators. It shouldn't be very complicated, but would be a great contribution.

**Comment by applikationsprogramvara** [comment]
If you don't want to extend the readme the information is a good candidate for wiki. Unfortunately it is not  publicly available in your repository. Would you mind to open it publicly or add me to your repository as a collaborator? Or you can merge the changes [from my fork](https://github.com/applikationsprogramvara/pdfview-android/wiki/How-is-is-working) via cloning, which I find not so nice.

**Comment by Dmitry-Borodin** [comment]
@applikationsprogramvara made wiki editing public. Let me know if I can do something else for you.

**Comment by Dmitry-Borodin** [comment]
Since now it's in wiki, does it make sense to add link to a wiki instead of pasting all the data in readme?

**Comment by Dmitry-Borodin** [comment]
Thank you!

**Pull request merged**
